### PR TITLE
Add asciidoc support

### PR DESCRIPTION
**Pull request by Tankanow**
I love your library! I am more familiar with the Asciidoc markup language so I added support for it. I also added some examples and necessary resources in the cryogen leiningen plugin project.

Cheers,

Adam

### CODE REVIEW

**Comment by Tankanow** [comment]
O.k. I should have some time to update the pull request this week.

Thanks for the feedback!

Cheers,

Adam

**Comment by lacarmen** [comment]
Excellent, I look forward to it!

**Comment by Tankanow** [comment]
OK ... I updated the pull request so that asciidoc engine honors the :toc flag and rewrites local hrefs. I split the rewrite-hrefs function so asciidoc processing could reuse the string replacement logic. 

Let me know if you have any questions about the changes to `make-links` that add support for header id attributes. I used `(or id name)` and `id` as the first operand to `or` because I think that is the order listed in the html5 spec.

**Comment by yogthos** [comment]
Fantastic work, it does looks like your branch might be a bit out of date, could you sync your pr to the latest.

**Comment by Tankanow** [comment]
Synced and a ran a sanity test with the example content I added to the `cryogen` leiningen plugin project.

**Comment by lacarmen** [comment]
Awesome :) I'll have a new release on clojars soon.

**Pull request merged**
